### ISSUE TITLE
chapter 6 /auth/twitter HTTP 500 error 

### ISSUE THREAD

**Issue by raibutera** [azat-co/practicalnode#10]
I'm having the same issue as in #5 

I have set my consumer key and consumer secret as appropriate in Makefile

Could you please go through what settings/permissions the Twitter app requires?

Even a very short and simple step-by-step of creating the app and setting up the permissions would be enough to get this working so we can continue reading the book!

**Comment by astemborskim** [comment]
I am experiencing similar issues with 500 error.. I have added the key and secret posted on the dev.twitter.com to the everyauth/Makefile in place of the 'AAAAAAAAAAA' and 'BBBBBBBBBBBBBBBBBB'  provided by defualt in the code. The only other change is I replaced azat_co for my twitter handle in the app.js file.

![capture1](https://cloud.githubusercontent.com/assets/4976923/5962729/86e85606-a7ab-11e4-838e-ae059dd5e430.JPG)
![capture](https://cloud.githubusercontent.com/assets/4976923/5962731/888f3ef2-a7ab-11e4-87e4-d978234df256.JPG)

**Comment by davestream** [comment]
Hi everyone I am working now with practicalNodejs and twitter login form then what was the final result of this issues because it is still open please any advance helping, thanks

**Comment by raibutera** [comment]
@sharstream we got no response. unfortunately @azat-co hasn't been too helpful to the people who have bought his book.

**Comment by shahar1** [comment]
Open your app settings via https://apps.twitter.com, then set up your Callback URL to: {path}/auth/twitter/callback/ 
(i.e., if you work on localhost it should be something like: http://127.0.0.1;3000/auth/twitter/callback/)

For more information: https://github.com/bnoguchi/everyauth

**Comment by azat-co** [comment]
there might be many things going here like username and key and callbacks... it's hard to debug with little information from you. the best bet is to turn on all the logs and debug step by step.

**Comment by moicez** [comment]
Had the same problem, here is my solution:
On the Twitter App Settings:
Website: http://127.0.0.1:3000/
Calback URL: http://127.0.0.1:3000/auth/twitter/callback/

**Comment by azat-co** [comment]
@moicez yes!

**Comment by vtthuan789** [comment]
Dear all,

Even I configured Twitter App Settings like @moicez said. I also replaced azat_co for my twitter handle. But it still experienced this error. 

Could you help me @azat-co ? Thank you.
