### ISSUE TITLE
CH 3 - Mocha tests fails

### ISSUE THREAD

**Issue by astemborskim** [azat-co/practicalnode#11]
I'm using the index.js and app.js raw code from git hub to run the mocha test. I'm recieving a timeout and failure when testing.
![package](https://cloud.githubusercontent.com/assets/4976923/5921045/908342da-a606-11e4-828b-c7842cab8d0b.JPG)

![chapter3mochafail](https://cloud.githubusercontent.com/assets/4976923/5921016/6ad89c7e-a606-11e4-9f77-5bea129a8c76.JPG)
![appjs](https://cloud.githubusercontent.com/assets/4976923/5921017/6c110ea0-a606-11e4-93ee-decafecc7c2d.JPG)
![indexjs](https://cloud.githubusercontent.com/assets/4976923/5921018/6d34d762-a606-11e4-92cf-afa020305406.JPG)

**Comment by astemborskim** [comment]
I'm not sure what was missing before. I but I recreated a express template and repasted the code. Now it is passing.

**Comment by azat-co** [comment]
:+1:
