### ISSUE TITLE
ch5 (git) - mongo-skin.js - TypeError: Object #<SkinClass> has no method 'findOneAndAddText'

### ISSUE THREAD

**Issue by nikolaygit** [azat-co/practicalnode#2]
Moving the file `mongo-skin.js` to the folder `blog-express/` and running `node mongo-skin.js` gives the following error:

(Using Node.js v0.10.31 and mongoDB 2.6.4)

``` javascript
db.collection('messages').findOneAndAddText('hi', function(count, id){
                          ^
TypeError: Object #<SkinClass> has no method 'findOneAndAddText'
    at Object.<anonymous> (/.../practicalnode/ch5/blog-express/mongo-skin.js:26:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by josevillacreses** [comment]
I got it working with a few changes:

var mongoskin = require('mongoskin'),
  dbHost = '127.0.0.1',
  dbPort = 27017;

var db = mongoskin.db('mongodb://' + dbHost + ':' + dbPort + '/local', {safe: true});

db.bind('messages').bind({
  findOneAndAddText: function (text, fn) {
    db.collection('messages').findOne({}, function (error, item) {
      if (error) {
        console.error(error);
        process.exit(1);
      }
      console.info("findOne: ", item);
      item.text = text;
      var id = item._id.toString(); // we can store ID in a string
      console.info("before saving: ", item);
      db.collection('messages').save(item, function (error, count) {
        console.info("save: ", count);
        return fn(count, id);
      });
    })
  }
});

db.messages.findOneAndAddText('hi', function (count, id) {
  db.collection('messages').find({
    _id: mongoskin.helper.toObjectID(id)
  }).toArray(function (error, items) {
    console.info("find: ", items);
    db.close();
    process.exit(0);
  });
});

**Comment by pkwenda** [comment]
HI,Im CHINA   In ch5    
node mongo-native-insert.js

db state:  connected
{ [MongoError: driver is incompatible with this server version] name: 'MongoError' }

what  to do？

my MongoDB -v ：  db version v3.2.6

**Comment by azat-co** [comment]
@nikolaygit @josevillacreses yes. mongoskin changed the way methods are created. bind().bind() will work. I updated it in new edition's code https://github.com/azat-co/practicalnode/blob/master/code/ch5/mongo-examples/mongo-skin.js

**Comment by azat-co** [comment]
@pkwenda maybe mongodb (npm module) version? check the new code at https://github.com/azat-co/practicalnode/blob/master/code/ch5/mongo-examples/mongo-native-insert.js after you install proper versions with `npm i`
