### ISSUE TITLE
ch5 (book) - missing scripts/css download description

### ISSUE THREAD

**Issue by nikolaygit** [azat-co/practicalnode#3]
In the book, there is no mention how to download the javascripts/css files, e.g. `bower install bootstrap#3.0.2` and `bower install jquery#2.0.3`. And if one follows the coding instructions without checking out the git source code, one does not see the final UI.

Also missing documentation: how to compile `styl` files to `css`. (e.g. `stylus -w public/css/style.styl`)

**Comment by azat-co** [comment]
bower might be gone. i don't see it in my new text. stylus is compiled by express. no need to compile it with cli
