### ISSUE TITLE
NEW TOPICS

### ISSUE THREAD

**Issue by azat-co** [azat-co/practicalnode#37]
Please vote on these topics to be included into the 2nd edition:

* http/2
* SSL
* NAPI (native modules)
* async/await, promises
* crypto
* Ethereum, dapps, web3
* React Native
* Electron
* Webpack
* ES6 modules in Node
* Babel
* Docker
* AWS
* k8s
* Axios
* Fetch API (node fetch npm module)
* GraphQL server
* TypeScript or Flow
* Yarn

**Comment by bboydflo** [comment]
docker +1

**Comment by syrianadus** [comment]
async/await, promises
NAPI (native modules)
http/2
Docker
+1

**Comment by jorgeorm** [comment]
- http/2
   - React Native
   - k8s
   - GraphQL server

+1

Don't know what Asixos is.

-------------------------------------------------------------------------------------
Jorge Ordoñez Mendez
Systems Engineer
Universidad del Valle

2017-11-08 9:40 GMT-05:00 Elias Yousef <notifications@github.com>:

**Comment by bboydflo** [comment]
@jorgeorm I think @azat-co meant to write [axios](https://github.com/mzabriskie/axios)

**Comment by jessewillardcom** [comment]
zone.js debugging

**Comment by stephanerotureau** [comment]
http/2
NAPI (native modules)
async/await, promises
Webpack
Babel
Docker
AWS
k8s
Axios
GraphQL server

**Comment by arpithparikh** [comment]
Ether,daaps and web3

**Comment by ptums** [comment]
Http/2
Capps
Docker
AWS
Webpack

**Comment by azat-co** [comment]
No one mentioned yarn so adding it there.

**Comment by Rictus** [comment]
Docker
Fetch API (node fetch npm module)
GraphQL server
+1

**Comment by JIBIN-P** [comment]
Async/await, promises
React Native
Webpack
Babel
Docker
AWS
GraphQL server

**Comment by sidgate** [comment]
http/2
NAPI (native modules)
async/await, promises
ES6 modules in Node
Docker
TypeScript or Flow
Yarn

**Comment by darwinbatres** [comment]
http/2
SSL
NAPI (native modules)
async/await, promises
crypto
Ethereum, dapps, web3
ES6 modules in Node
Docker
AWS
k8s
GraphQL server
TypeScript or Flow

**Comment by cblanto7** [comment]
Docker
AWS
SSL
Crypto

**Comment by azat-co** [comment]
CC @syrianadus

**Comment by arhuman** [comment]
http/2
NAPI (native modules)
async/await, promises
Ethereum, dapps, web3
Webpack
Docker
Fetch API (node fetch npm module)
Yarn

**Comment by cymegerm** [comment]
http/2
SSL
NAPI (native modules)
Ethereum, dapps, web3
React Native
Docker
AWS
k8s
Fetch API (node fetch npm module)
GraphQL server
TypeScript

**Comment by hafeez-syed** [comment]
NAPI (native modules)
    async/await, promises
    crypto
    Ethereum, dapps, web3
    Webpack
    Docker
    GraphQL server
    TypeScript
    Node.js microservices (just a suggestion)

**Comment by MWallin** [comment]
http/2
SSL
async/await, promises
Webpack
ES6 modules in Node
Babel
Docker
AWS
Fetch API (node fetch npm module)
GraphQL server

**Comment by fsebbah** [comment]
Node.js microservices
http/2
SSL
NAPI (native modules)

**Comment by azat-co** [comment]
@MWallin fetch is very low-level. developer have to stringify and supply application/json headers. Why would anyone use it over axios if fetch is not natively supported in node (I mean you still have to npm install a package so why not install axios?)

**Comment by azat-co** [comment]
@hafeez-syed how "Node.js microservices" is new or different from build a small Express app? I mean Node.js microservices is just an Express app with one resource like /users or /documents

you can wrap them in container but you don't have to

you can use serverless but you don't have to

Please clarify

**Comment by azat-co** [comment]
@jessewillardcom why would someone use zone.js and debug it?

**Comment by jessewillardcom** [comment]
Explain how it is used in debugging...

**Comment by WolffDev** [comment]
http/2
SSL
async/await, promises
Webpack
ES6 modules in Node
Babel
Docker
AWS
Fetch API (node fetch npm module)
GraphQL server
Node.js microservices

**Comment by alikahwaji** [comment]
React Native
Async/await, promises
Webpack
Babel
ES6 modules in Node
TypeScript
Yarn

**Comment by MWallin** [comment]
@azat-co My thinking is that fetch is a new api and therefore more intresting than axios which is a layer on top of XMLHttpRequest. The base apis I think are more intresting to learn about than libraries, if I know the basics than I can use the libraries built on top of them more effectivley. 

However, in my actual application I would probably end up using axios anyway so I guess Im kind of split on the subject. Maybe include both too better illustrate why one is better than the other?

**Comment by naveedjb** [comment]
http/2
SSL
async/await, promises
Webpack
ES6 modules in Node
Babel
Docker
AWS
Fetch API (node fetch npm module)
GraphQL server
Node.js microservices

**Comment by azat-co** [comment]
FYI the manuscript is due on Jan 6 so all changes and text needs to be done by then

**Comment by azat-co** [comment]
![img_5559](https://user-images.githubusercontent.com/1137314/34191672-aeaf1bac-e56a-11e7-9bed-7c4369f5784b.JPG)

**Comment by azat-co** [comment]
I wrote these 4 new chapters. :)

13. [Node HTTP/2 Servers](https://github.com/azat-co/practicalnode/blob/master/chapter13/chapter13.md) BRAND NEW 
14. [Asynchronous Code in Node](https://github.com/azat-co/practicalnode/blob/master/chapter14/chapter14.md) BRAND NEW
15. [Node Microservices with Docker and AWS ECS](https://github.com/azat-co/practicalnode/blob/master/chapter15/chapter15.md)  BRAND NEW 
16. [Serverless Node with AWS Lambda](https://github.com/azat-co/practicalnode/blob/master/chapter16/chapter16.md)  BRAND NEW
