### ISSUE TITLE
ch5 (book-git) - Mocha test fails on mismatching articles.json in the book and the git source

### ISSUE THREAD

**Issue by nikolaygit** [azat-co/practicalnode#4]
If one:
- has two projects, one coded from the book (book project) and another one from git (git project)
- runs `./db/seed.sh` from the git project.
- runs `make test` from the book project.

then one test will fail because the first article in the book ends with `to improve network coverage...` and it does not match the string from the git project `to improve network coverage.`

Possible solution is to finish the article sentence in the book with a dot, even when the strings are longer.

**Comment by azat-co** [comment]
@nikolaygit I fixed it by adding a note to use Git version
