### ISSUE TITLE
Invalid Display URL

### ISSUE THREAD

**Issue by aggarwaldeepak** [azat-co/practicalnode#45]
The display URL (https://github.com/maxogden/art-of-node%23callbacks) at [Taming Callbacks in Node.js](https://github.com/azat-co/practicalnode/blob/master/chapter1/chapter1.md#taming-callbacks-in-nodejs) is invalid. However _Callbacks_ refers to the right URL(https://github.com/maxogden/art-of-node#callbacks).

**Comment by azat-co** [comment]
Should be fixed now
