### ISSUE TITLE
serverless examples use outdated dynamodb-doc

### ISSUE THREAD

**Issue by constb** [azat-co/practicalnode#47]
A note in its repository says:

```As of September 10, 2015, this version of the Document SDK will be deprecated in favor of the AWS.DynamoDB.DocumentClient in the official AWS SDK for JavaScript```

I believe examples should be updated...

**Comment by azat-co** [comment]
@constb you are confused by sdk. i'm not using sdk. i'm using dynamodb-doc. There's NOT deprecation of any kind on its repository or npm: https://www.npmjs.com/package/dynamodb-doc

**Comment by azat-co** [comment]
@constb thank you for commenting. i understand it's bad to have outdated example. you are confusing doc with sdk. i'm not using sdk. i'm using dynamodb-doc. There's NOT deprecation of any kind on its repository or npm: https://www.npmjs.com/package/dynamodb-doc
